version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: orderslist
    container_name: orderslist-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - orderslist
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: orderslist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: orderslist
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
      MYSQL_USER: sf
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - orderslist
  nginx:
    image: nginx:1.17-alpine
    container_name: orderslist-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - orderslist

networks:
  orderslist:
    driver: bridge
