version: '3'

services:

  db:
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - 3306:3306
    container_name: orderslist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: orderslist
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
      MYSQL_USER: sf
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    depends_on:
      - php
    networks:
      - orderslist

  nginx:
    image: nginx:latest
    container_name: orderslist-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - orderslist
    depends_on:
      - php

  php:
    container_name: orderslist-php
    build:
      args:
        user: user
        uid: 1000
      context: ./docker-compose/php
    volumes:
      - ./:/var/www
      - ./docker-compose/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=mytestservername
    networks:
      - orderslist

networks:
  orderslist:
    driver: bridge